version: '3.8'
services:
  db:
    build: ./database/
    environment:
      POSTGRES_PASSWORD: secret-test
      POSTGRES_USER: user-test
      POSTGRES_DB: gonito-test
      DB_USER: user-test
      DB_PASS: secret-test
    ports:
      - 5432:5432
    volumes:
      - ./database/create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - /code/store
