version: '3.8'
services:
  db:
    build: ./database/
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - ./database/create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - KEY=${KEY}
      - ALGORITHM=${ALGORITHM}
      - STORE_PATH=${STORE_PATH}
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - /code/store
